### ISSUE TITLE
PLL1 clock patch

### ISSUE THREAD

**Issue by guillaumef** [linux-sunxi/u-boot-sunxi#17]
Hi Henrik,

After many tests around, this patch suggested from tom cubbie corrects a wrong clock init corrupting the kernel stack (seems linked with new A10)

https://github.com/hno/uboot-allwinner/blob/sun4i/arch/arm/include/asm/arch-sunxi/clock.h#L141
change
# define PLL1_FACTOR_N 21

to
# define PLL1_FACTOR_N 16

There is many forum threads around about same issues and leaking in linux-allwinner issues... and i'm pretty sure it's coming from this.
My last tests are here:
http://forum.doozan.com/read.php?6,9527,9634#msg-9634

It could save a lot of time and disappointment to newcomers (like it could have same me many hours ;) to patch it.

Regards,
Guillaume

**Comment by hno** [comment]
The clocking is being reworked completely.

The original values are correct for 1GHz operation but is missing
voltage settings in the PMU causing random system crashes due to the arm
core running under voltage for the set frequency.

Current code runs the CPU core at a safe frequency until PMU can be set
up proper.

lör 2012-09-29 klockan 17:00 -0700 skrev Guillaume Fougnies:

**Comment by hno** [comment]
Please se current sunxi branch (default). clock support have been reworked significantly and PMU support added. Should fix your issues.

There is no board definiiton for mk802 yet but the mele_a1000 config probably works.
