### ISSUE TITLE
Can't find support for allwinner sun4i

### ISSUE THREAD

**Issue by radagasp** [linux-sunxi/u-boot-sunxi#39]
It does not appear in under /boards.
 I followed this guide 
http://linux sunxi.org/FirstSteps#The_flexible_option:_manual_build_and_installation

I am compiling towards the cubieboard

please to help

**Comment by oliv3r** [comment]
This is really really the wrong spot to ask half a question.

http://linux-sunxi.org has a mailing list and an IRC channel where this would be far more appropiate.

Trying to guess what your question is, looking at:
https://github.com/linux-sunxi/u-boot-sunxi/blob/sunxi/board/sunxi/dram_cubieboard.c

I find the cubieboard just fine. It is also defined in the boards.cfg.

Since the cubieboard 1.0 is VERY common amongst the developers, I pretty much can guarantee you it 'just works'.

Maybe try the BSP as that does a lot of things automatically for you.

**Comment by Abirosvaldo** [comment]
hi,
I have the source code android to device A10s.

I can generate the image, at compile time  does not give any error.
I use program LiveSuit to record in memory Nand.
when I call the device appears the image of  "initlogo.rle", the image disappears, but not give sequence.

you know what can be?

**Comment by oliv3r** [comment]
But this repository is about u-boot and u-boot does not have any video output support at all.

**Comment by Abirosvaldo** [comment]
hi,
Can you tell me what I should install on linux to compile the Kernel.

I created a new virtual machine,  but something is missing to compile the kernel ..

**Comment by oliv3r** [comment]
Ask in the appropiate place, either the linux-sunxi mailing list or the linux-sunxi IRC channel. This is not a support forum, this is a bug tracker/place to submit patches. Also, read linux-sunxi.org, we have all this information plentiful documented there.

**Comment by Abirosvaldo** [comment]
thanks..
