### ISSUE TITLE
Pull down peripheral support for upstream

### ISSUE THREAD

**Issue by RandomInsano** [linux-sunxi/u-boot-sunxi#78]
Hey folks!

For fun, I went and built u-boot from upstream. It turns out that pretty much all of the features of the A10 on the Cubieboard are working magnificently well (except for onboard flash as you'd expect). I can `fatload` images from USB, SATA, SD, and seemingly network.

The problem for me booting OpenBSD seems to that it can't actually start the kernel I load into memory. It might be me being to naïve, or it might be straight up broken. It does work from this branch though.

I think the biggest feature here for a lot of people would be to be able to boot from USB and SATA so they can just flash u-boot onto the NAND.

So, feature request to enable USB support in your branch if possible. I haven't actually tried just enabling it in the build options yet.

**Comment by oliv3r** [comment]
A more sensible solution would be to add SPI u-boot support to mainline (i've got htis on my plate for over a year now ;)

With SPI booting, you can have u-boot living in spi, + kernel if you want, and then boot from wherever you want. Flash will be problematic for the forseable future, and the sunxi-u-boot repository should be considerer maintainance only, since we have almost everything in mainline as it is. I don't think anybody wants or intends to keep sunxi-u-boot alive for longer then it is required.

**Comment by RandomInsano** [comment]
Glad to hear that mainlining the special sauce here is the plan.

Do you have any notes on what this SPI booting stuff is and what's needed to get it upstream?
